// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fduqtvljaoahcecihfft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdXF0dmxqYW9haGNlY2loZmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODc0MTgsImV4cCI6MjA1OTE2MzQxOH0.F1yrK7fcm9ugRpgL-xhyBad9hBXxoTlVJXO8IAKaKds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);